import Link from "next/link";
import { ArrowUpRight, Download, ChevronRight } from "lucide-react";
import { Card, MoneyCell, StatusPill } from "@stoa/ui";

const properties = [
  { id: "P-2417", name: "2417 Telegraph Ave", city: "Oakland · 4 units", occ: 1.0, ytd: 1152000, last_distribution: "Apr 6", status: "current" },
  { id: "P-1842", name: "1842 College Ave", city: "Berkeley · 8 units", occ: 0.875, ytd: 2390000, last_distribution: "Apr 6", status: "current" },
  { id: "P-3120", name: "3120 Adeline St", city: "Oakland · 6 units", occ: 1.0, ytd: 1820000, last_distribution: "Apr 6", status: "current" },
];

export default function OwnerHome() {
  return (
    <div className="space-y-12">
      <div className="flex items-baseline justify-between">
        <div>
          <p className="font-mono text-overline uppercase tracking-[0.16em] text-text-muted">April 2026</p>
          <h1 className="mt-2 font-display text-[44px] tracking-tight text-text-primary">
            Hello, Carla.
          </h1>
          <p className="mt-2 text-[16px] text-text-secondary">
            Q1 distributions cleared. One approval needs your eye.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button className="inline-flex items-center gap-2 rounded-md border border-[var(--border-subtle)] px-3 py-2 text-[13px] text-text-secondary hover:bg-[var(--surface-paper)]">
            <Download className="h-3.5 w-3.5" /> Statement
          </button>
          <Link href="/owner/approvals" className="rounded-md bg-brass-500 px-3 py-2 text-[13px] font-medium text-ink-900 hover:bg-brass-600">
            Review 1 approval
          </Link>
        </div>
      </div>

      {/* Stat row, editorial */}
      <div className="grid grid-cols-4 gap-px overflow-hidden rounded-2xl bg-[var(--border-subtle)] shadow-hairline">
        <Stat
          label="Net cash · April"
          value={<MoneyCell cents={865200} size="lg" intent="success" />}
          subtitle="$ 720 above March"
        />
        <Stat
          label="YTD distributions"
          value={<MoneyCell cents={5362000} size="lg" />}
          subtitle="+4.4% vs YTD 2025"
        />
        <Stat
          label="Occupancy"
          value={<span className="font-mono tabular text-[32px] text-text-primary">94.4<span className="text-[18px] text-text-muted">%</span></span>}
          subtitle="17 of 18 units"
        />
        <Stat
          label="Open work orders"
          value={<span className="font-mono tabular text-[32px] text-text-primary">2</span>}
          subtitle="both within budget"
        />
      </div>

      {/* April statement card */}
      <div className="grid grid-cols-[1.4fr_1fr] gap-8">
        <Card padding="lg">
          <div className="flex items-baseline justify-between">
            <div>
              <p className="text-overline text-text-muted">April 2026 statement</p>
              <h2 className="mt-1 font-display text-[26px] text-text-primary">Performance summary</h2>
            </div>
            <span className="text-[12px] font-mono text-text-muted">Generated by Owner Reporting · 0.6s</span>
          </div>

          <p className="mt-5 max-w-prose text-[15px] leading-[24px] text-text-secondary">
            All three properties collected on time. 2417 Telegraph saw a $185 electrical
            repair (within lease threshold, no owner action needed). One unit at 1842
            College is vacating June 1 — Leasing is preparing the listing draft for your
            review.
          </p>

          <div className="mt-7 grid grid-cols-2 gap-5">
            <Line label="Rents collected" cents={1038400} />
            <Line label="Mgmt fees" cents={83000} intent="default" sign="−" />
            <Line label="Maintenance" cents={18500} intent="default" sign="−" />
            <Line label="Operating expenses" cents={71700} intent="default" sign="−" />
            <Line label="Reserve contribution" cents={0} intent="muted" />
            <Line label="Net to owner" cents={865200} intent="success" emphasis />
          </div>

          <div className="mt-7 flex gap-2">
            <Link href="/owner/statements/april-2026" className="rounded-md bg-[var(--surface-paper)] px-3 py-2 text-[13px] text-text-secondary shadow-hairline hover:shadow-md">
              Open statement
            </Link>
            <button className="inline-flex items-center gap-1.5 rounded-md px-3 py-2 text-[13px] text-text-secondary hover:bg-[var(--surface-paper)]">
              <Download className="h-3.5 w-3.5" /> CSV · PDF
            </button>
          </div>
        </Card>

        <div className="space-y-5">
          <Card>
            <p className="text-overline text-text-muted">Awaiting your decision</p>
            <h3 className="mt-1 font-display text-[20px] text-text-primary">
              Lease renewal · Unit 5 · 1842 College
            </h3>
            <p className="mt-3 text-[14px] leading-[22px] text-text-secondary">
              Diego R. has been a tenant for 28 months. Stoa recommends a renewal at
              <span className="font-mono tabular"> $3,150 </span>(+3.3%, within the
              AB-1482 cap of 8.0%). Market data: similar units leased for $3,090–$3,220
              over the last 60 days.
            </p>
            <div className="mt-4 flex gap-2">
              <button className="rounded-md bg-brass-500 px-3 py-1.5 text-[13px] font-medium text-ink-900 hover:bg-brass-600">
                Approve
              </button>
              <button className="rounded-md border border-[var(--border-subtle)] px-3 py-1.5 text-[13px] text-text-secondary hover:bg-[var(--surface-paper)]">
                Counter
              </button>
              <button className="rounded-md px-3 py-1.5 text-[13px] text-text-secondary hover:bg-[var(--surface-paper)]">
                Decline
              </button>
            </div>
          </Card>

          <Card>
            <p className="text-overline text-text-muted">Trust account</p>
            <div className="mt-2 flex items-baseline gap-3">
              <MoneyCell cents={1860000} size="lg" />
              <span className="text-[11px] font-mono text-[var(--signal-success-fg)]">▲ reconciled</span>
            </div>
            <ul className="mt-4 space-y-2 text-[13px] text-text-secondary">
              <li className="flex justify-between"><span>Deposits held</span><MoneyCell cents={1440000} size="sm" /></li>
              <li className="flex justify-between"><span>Q1 reserve</span><MoneyCell cents={300000} size="sm" /></li>
              <li className="flex justify-between"><span>Pending distribution</span><MoneyCell cents={120000} size="sm" /></li>
            </ul>
            <Link href="#" className="mt-4 inline-flex items-center gap-1 text-[13px] text-brass-700">View ledger <ChevronRight className="h-3.5 w-3.5" /></Link>
          </Card>
        </div>
      </div>

      {/* Property roll */}
      <div>
        <div className="mb-4 flex items-baseline justify-between">
          <h2 className="font-display text-[26px] text-text-primary">Your portfolio</h2>
          <Link href="/owner/properties" className="text-[13px] text-brass-700 underline-draw">All 3 properties</Link>
        </div>
        <div className="overflow-hidden rounded-2xl bg-[var(--surface-paper)] shadow-hairline divide-y divide-[var(--border-subtle)]">
          <div className="grid grid-cols-[1.6fr_1fr_1fr_1fr_auto] gap-4 px-6 py-3 text-overline text-text-muted">
            <div>Property</div><div>Occupancy</div><div>YTD net</div><div>Last distribution</div><div></div>
          </div>
          {properties.map((p) => (
            <Link
              key={p.id}
              href={`/owner/properties/${p.id.toLowerCase()}`}
              className="grid grid-cols-[1.6fr_1fr_1fr_1fr_auto] items-center gap-4 px-6 py-4 hover:bg-cream-50"
            >
              <div>
                <div className="text-[14.5px] font-medium text-text-primary">{p.name}</div>
                <div className="text-[12px] text-text-muted">{p.city}</div>
              </div>
              <div className="text-[14px] tabular font-mono text-text-primary">
                {(p.occ * 100).toFixed(1)}%
              </div>
              <MoneyCell cents={p.ytd} size="sm" intent="success" />
              <div className="text-[13px] text-text-secondary font-mono tabular">{p.last_distribution}</div>
              <ChevronRight className="h-4 w-4 text-text-muted" />
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}

function Stat({
  label,
  value,
  subtitle,
}: {
  label: string;
  value: React.ReactNode;
  subtitle?: string;
}) {
  return (
    <div className="bg-[var(--surface-paper)] px-6 py-5">
      <div className="text-overline text-text-muted">{label}</div>
      <div className="mt-2">{value}</div>
      {subtitle ? (
        <div className="mt-1 inline-flex items-center gap-1 text-[12px] text-text-muted">
          <ArrowUpRight className="h-3 w-3 text-[var(--signal-success-fg)]" />
          {subtitle}
        </div>
      ) : null}
    </div>
  );
}

function Line({
  label,
  cents,
  intent = "default",
  sign = "",
  emphasis = false,
}: {
  label: string;
  cents: number;
  intent?: "default" | "success" | "muted";
  sign?: string;
  emphasis?: boolean;
}) {
  return (
    <div className={["flex items-baseline justify-between", emphasis ? "border-t border-[var(--border-subtle)] pt-4 col-span-2" : ""].join(" ")}>
      <span className={emphasis ? "font-display text-[18px] text-text-primary" : "text-[14px] text-text-secondary"}>
        {label}
      </span>
      <span className="flex items-baseline gap-1">
        {sign ? <span className="text-text-muted text-[14px]">{sign}</span> : null}
        <MoneyCell cents={cents} size={emphasis ? "md" : "sm"} intent={intent} />
      </span>
    </div>
  );
}
