import type { Config } from "tailwindcss";
import { palette, radius, shadow, space } from "./tokens";

const preset: Partial<Config> = {
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        cream: palette.cream,
        ink: palette.ink,
        brass: palette.brass,
        red: palette.red,
        green: palette.green,
        amber: palette.amber,

        // semantic tokens (light mode default; dark via CSS vars in globals.css)
        canvas: "var(--surface-canvas)",
        paper: "var(--surface-paper)",
        app: "var(--surface-app)",
        sunken: "var(--surface-sunken)",
        inverse: "var(--surface-inverse)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-muted": "var(--text-muted)",
        "text-placeholder": "var(--text-placeholder)",
        "text-inverse": "var(--text-inverse)",
        "border-subtle": "var(--border-subtle)",
        "border-default": "var(--border-default)",
        "border-strong": "var(--border-strong)",
        "border-focus": "var(--border-focus)",
        "accent-bg": "var(--accent-bg)",
        "accent-bg-hover": "var(--accent-bg-hover)",
        "accent-bg-pressed": "var(--accent-bg-pressed)",
        "accent-fg": "var(--accent-fg)",
      },
      fontFamily: {
        display: ['"GT Sectra"', '"Tiempos Headline"', '"PT Serif"', "Georgia", "serif"],
        sans: ['"Inter"', '"General Sans"', "system-ui", "-apple-system", '"Segoe UI"', "sans-serif"],
        mono: ['"JetBrains Mono"', '"IBM Plex Mono"', "ui-monospace", '"SF Mono"', "monospace"],
      },
      fontSize: {
        "display-2xl": ["72px", { lineHeight: "76px", letterSpacing: "-0.015em", fontWeight: "440" }],
        "display-xl": ["56px", { lineHeight: "60px", letterSpacing: "-0.015em", fontWeight: "440" }],
        "display-lg": ["44px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "460" }],
        "display-md": ["36px", { lineHeight: "42px", letterSpacing: "-0.015em", fontWeight: "500" }],
        h1: ["32px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" }],
        h2: ["24px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }],
        h3: ["20px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        h4: ["17px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "26px", fontWeight: "400" }],
        body: ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        overline: ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" }],
        "mono-lg": ["17px", { lineHeight: "24px", fontWeight: "500" }],
        mono: ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "mono-sm": ["12px", { lineHeight: "18px", fontWeight: "500" }],
      },
      spacing: {
        0: space[0],
        px: space.px,
        0.5: space["0.5"],
        1: space[1],
        1.5: space["1.5"],
        2: space[2],
        3: space[3],
        4: space[4],
        5: space[5],
        6: space[6],
        8: space[8],
        10: space[10],
        12: space[12],
        16: space[16],
        20: space[20],
        24: space[24],
        32: space[32],
      },
      borderRadius: {
        none: radius.none,
        sm: radius.sm,
        md: radius.md,
        lg: radius.lg,
        xl: radius.xl,
        "2xl": radius["2xl"],
        full: radius.pill,
      },
      boxShadow: {
        hairline: shadow.hairline,
        sm: shadow.sm,
        md: shadow.md,
        lg: shadow.lg,
        xl: shadow.xl,
      },
      transitionTimingFunction: {
        "stoa-base": "cubic-bezier(0.4, 0, 0.2, 1)",
        "stoa-out": "cubic-bezier(0.22, 1, 0.36, 1)",
        "stoa-hero": "cubic-bezier(0.16, 1, 0.3, 1)",
      },
      transitionDuration: {
        80: "80ms",
        120: "120ms",
        180: "180ms",
        320: "320ms",
        600: "600ms",
      },
      maxWidth: {
        content: "1200px",
        wide: "1440px",
        tenant: "480px",
        prose: "880px",
      },
    },
  },
  plugins: [],
};

export default preset;
